### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by nord** [fwenzel/django-sha2#2]
Hi Fred,

I have installed the patch using easy_install and added AUTHENTICATION_BACKENDS and BCRYPT_ROUNDS to my settings.py file as well as HMAC_KEYS to my settings_local.py.

However the code does not seem to be run and patch Django unless I explicitly call it in my application:

<code>from django_sha2.auth import BcBackend</code>

Am I missing something here?

**Comment by nord** [comment]
I guess I could add "django_sha2" to my "INSTALLED_APPS", is that correct? If so, could you pls update the README.md file?

Thanks for the good work.

**Comment by fwenzel** [comment]
nord: Thanks for bringing that to my attention! I think that's indeed what's needed to load the patch properly. I will add this to the readme file.

Let me know if you see any problems with this. I haven't been able to extensively test it yet (let alone used it in a production application).

**Comment by fwenzel** [comment]
Also, you might not have a settings_local.py file, as it is not present in Django by default. If you do add such a file, make sure to `from settings_local import *` at the end of your regular `settings.py` file.

**Comment by fwenzel** [comment]
Done! https://github.com/fwenzel/django-sha2/commit/ae3f31ae95f3d73d27a438e4921db53205756dfa

**Comment by nord** [comment]
Thanks, works great so far.
